### PR TITLE
fix bad #emit placement near 'if' statements

### LINKED ISSUE #319: `#emit` stuck in previous block
**Is this a BUG REPORT, FEATURE REQUEST or QUESTION?**:

* [x] Bug Report
* [ ] Feature Request
* [ ] Question

**What happened**:

```pawn
new a;
if (FALSE)
    printf("hi");
#emit CONST.pri 42
#emit STOR.S.pri a
printf("%d", a);
```

Prints 0.

**What you expected to happen**:

Print 42.

**How to reproduce it (as minimally and precisely as possible)**:

^

**Anything else we need to know?**:

The `#emit` code isn't properly scoped, so compiles as:

```pawn
new a;
if (FALSE)
{
    printf("hi");
    #emit CONST.pri 42
    #emit STOR.S.pri a
}
printf("%d", a);
```

I didn't use explicit braces, but that doesn't matter.  You can fix it with extra braces:

```pawn
new a;
if (FALSE)
{
    printf("hi");
}
{}
#emit CONST.pri 42
#emit STOR.S.pri a
printf("%d", a);
```

I thought this was fixed long ago, but I just spent ages tracking down a bug that turned out to be caused by this.

**Environment**:

* Operating System
* Compiler version
* How are you invoking the compiler? Pawno, Sublime, vscode, sampctl or command-line?
* If using sampctl, the version number

### PR DESCRIPTION
**Pull request by YashasSamaga**
**What this PR does / why we need it**:

> /*
>   ** The 'statement()' takes care of generating the code inside the TRUE
>   ** branch. When it returns, the entire TRUE block would have its
>   ** code generated. 'matchtoken()' is called to look for an ELSE
>   ** branch. If there isn't an ELSE branch, the false branch label is put.
>   ** But the 'matchtoken()' function calls 'lex()' which in turn invokes
>   ** the preprocessor. If there are #emit directives present, the preprocessor
>   ** dumps those instructions. This would cause these instructions to appear
>   ** before the false label, i.e. the instructions appear in the TRUE branch
>   ** even though they are outside the TRUE branch.
>   **
>   ** To deal with this, we assume that there is no ELSE branch and add the false
>   ** label into the staging buffer. Thereby, any #emit instructions present will end
>   ** up in the false branch.
>   **
>   ** In case, there is an 'else' statement following 'if', then
>   ** we flush the staging buffer (which removes the #emit instructions
>   ** along with the false label). The label is supposed to be removed as the 'else'
>   ** branch handling code will add the false label again after a jump instruction.
>   ** The #emit instructions are also removed forever but that is not our concern
>   ** because it has been wrongly placed and the programmer needs to fix it.
>   **
>   ** if(expr) { }
>   ** #emit NOP // this is meaningless, the programmer has to fix the code
>   ** else { }
>   **
>   ** - Yashas
>   */

**Which issue(s) this PR fixes**:

Fixes #319 

**What kind of pull this is**:

* [x] A Bug Fix
* [ ] A New Feature
* [ ] Some repository meta (documentation, etc)
* [ ] Other

### CODE REVIEW

**Comment by YashasSamaga** [comment]
**Test:**
```
new a;
main () {
	if(a)
	{
    	#emit CONST.pri 1
    	#emit CONST.pri 2
	}
	#emit CONST.pri 3
	#emit CONST.pri 4
	
	if(a)
		a = 1;
	#emit CONST.pri 5
 	#emit CONST.pri 6
	
	if(a)
	{
	
	}
	#emit CONST.pri 7
	#emit CONST.pri 8
	
	if(a)
	{
		#emit CONST.pri 9
		#emit CONST.pri 10
 	}
 	else
 	{
 	    #emit CONST.pri 11
 	    #emit CONST.pri 12
 	}
 	#emit CONST.pri 13
 	#emit CONST.pri 14

 	if(0)
	{
    	#emit CONST.alt 1
    	#emit CONST.alt 2
	}
	#emit CONST.alt 3
	#emit CONST.alt 4

	if(0)
		a = 1;
	#emit CONST.alt 5
 	#emit CONST.alt 6

	if(0)
	{

	}
	#emit CONST.alt 7
	#emit CONST.alt 8

	if(0)
	{
		#emit CONST.alt 9
		#emit CONST.alt 10
 	}
 	else
 	{
 	    #emit CONST.alt 11
 	    #emit CONST.alt 12
 	}
 	
 	
 	#emit NOP
 	#emit NOP
 	
 	if(1)
 	{
 	    #emit LCTRL 1
 	    #emit LCTRL 2
 	}
 	#emit LCTRL 3
 	#emit LCTRL 4
 	else
 	{
 	    #emit LCTRL 5
 	    #emit LCTRL 6
 	}
}
```

**Output:**
```

CODE 0	; 0
;program exit point
	halt 0


DATA 0	; 0
dumpn 0 1

CODE 0	; 8
	proc	; main
	; line 2
	; line 3
	break	; c
	load.pri 0
	jzer 0
	;$exp
	const.pri 1
	const.pri 2
l.0
	const.pri 3
	const.pri 4
	; line b
	break	; 40
	load.pri 0
	jzer 1
	;$exp
	; line c
	break	; 54
	const.pri 1
	stor.pri 0
	;$exp
l.1
	const.pri 5
	const.pri 6
	; line 10
	break	; 78
	load.pri 0
	jzer 2
	;$exp
l.2
	const.pri 7
	const.pri 8
	; line 17
	break	; 9c
	load.pri 0
	jzer 3
	;$exp
	const.pri 9
	const.pri a
	jump 4
l.3
	const.pri b
	const.pri c
l.4
	const.pri d
	const.pri e
	; line 24
	break	; e8
	jump 5
	const.alt 1
	const.alt 2
l.5
	const.alt 3
	const.alt 4
	; line 2c
	break	; 114
	jump 6
	; line 2d
	break	; 120
	const.pri 1
	stor.pri 0
	;$exp
l.6
	const.alt 5
	const.alt 6
	; line 31
	break	; 144
	jump 7
l.7
	const.alt 7
	const.alt 8
	; line 38
	break	; 160
	jump 8
	const.alt 9
	const.alt a
	jump 9
l.8
	const.alt b
	const.alt c
l.9
	nop 
	nop 
	; line 47
	break	; 19c
	lctrl 1
	lctrl 2
	jump b
l.a
	lctrl 5
	lctrl 6
l.b
	zero.pri
	retn


STKSIZE 1000
```

**Comment by YashasSamaga** [comment]
A suitable error needs to be added for code like these:

```
if(expr) {

}
#emit NOP
else {

}
```

**Comment by Y-Less** [comment]
This is incomplete.

**Comment by YashasSamaga** [comment]
```
new a;
main () {
	if(a)
	{
    	#emit CONST.pri 1
    	#emit CONST.pri 2
	}
	#emit CONST.pri 3
	#emit CONST.pri 4

	if(a)
		a = 1;
	#emit CONST.pri 5
 	#emit CONST.pri 6

	if(a)
	{

	}
	#emit CONST.pri 7
	#emit CONST.pri 8

	if(a)
	{
		#emit CONST.pri 9
		#emit CONST.pri 10
 	}
 	else
 	{
 	    #emit CONST.pri 11
 	    #emit CONST.pri 12
 	}
 	#emit CONST.pri 13
 	#emit CONST.pri 14

 	if(0)
	{
    	#emit CONST.alt 1
    	#emit CONST.alt 2
	}
	#emit CONST.alt 3
	#emit CONST.alt 4

	if(0)
		a = 1;
	#emit CONST.alt 5
 	#emit CONST.alt 6

	if(0)
	{

	}
	#emit CONST.alt 7
	#emit CONST.alt 8

	if(0)
	{
		#emit CONST.alt 9
		#emit CONST.alt 10
 	}
 	else
 	{
 	    #emit CONST.alt 11
 	    #emit CONST.alt 12
 	}


 	#emit NOP
 	#emit NOP

 	if(1)
 	{
 	    #emit LCTRL 1
 	    #emit LCTRL 2
 	}
 	#emit LCTRL 3
 	#emit LCTRL 4
 	else
 	{
 	    #emit LCTRL 5
 	    #emit LCTRL 6
 	}
}
```

```
test.pwn(36) : warning 205: redundant code: constant expression is zero
test.pwn(44) : warning 205: redundant code: constant expression is zero
test.pwn(49) : warning 205: redundant code: constant expression is zero
test.pwn(56) : warning 205: redundant code: constant expression is zero
test.pwn(71) : warning 206: redundant test: constant expression is non-zero
test.pwn(78) : error 029: invalid expression, assumed zero
```

I don't like this but there's no other way out. The preprocessor should never affect syntax and code generation but Pawn uses a preprocessor directive instead of a statement for inline assembly.

**Comment by YashasSamaga** [comment]
This PR is ready to be merged. The current testing setup does not provide any means to verify assembly output.

Requires approval @pawn-lang/compiler @Daniel-Cortez

**Review by Southclaws — APPROVED** [review]

**Comment by YashasSamaga** [comment]
How do we add a test for this?

**Comment by Zeex** [comment]
Need to add a new test type to compare assembly output with expected code, can't do this right now.

**Pull request closed without merging**
