### PR TITLE
Tokenisation operator

### PR DESCRIPTION
**Pull request by VVWVV**
#155
Example:
```pawn
#define foo(%1,%2) %1##%2

main() {
    new barbaz;
    printf("%d", foo(bar, baz));
}
```

### CODE REVIEW

**Comment by Zeex** [comment]
This patch needs to check if the `##` is inside a string literal because:

```pawn
print("##");
```

^ will print `(null)`.

**Comment by Crytrax** [comment]
This patch breaks YSI. The following is the compiler's output.
```
Dependencies\CoreUtils\YSI\Init\..\YSI_Server\..\YSI_Data\..\YSI_Internal\..\YSI_Core\..\YSI_Coding\y_va.inc(112) : error 027: invalid character constant
```
Can anyone else confirm that this is not just some mistake on my end?

**Comment by Dayvison** [comment]
This commit 0786aed is breaking

**Comment by Crytrax** [comment]
Commit https://github.com/Zeex/pawn/pull/205/commits/f59b285e171eaf00a589df072597ded58d5be5bb fixes this. Thanks @VVWVV

**Comment by Y-Less** [comment]
One thing to be aware of, as I've seen this a few times:

```pawn
#define COLOR_RED #FF0000

SendClientMessage(playerid, COLOR_GREEN, "Hello {"#COLOR_RED"} world");
```

Not sure what would happen there.  But it shouldn't be too hard to avoid by skipping backtracking too much when you do symbol replacements.

**Comment by Zeex** [comment]
If you're going to work on this and re-submit, please also include a test that covers as much test cases as you can think of. For example, `##` inside macros, outisde of macros, with spaces around and without, insides strings and outside, and so on.

We're starting to add compile and crash tests for new issues (and hopefully runtime tests soon). See [source/compiler/tests](https://github.com/Southclaws/pawn/tree/master/source/compiler/tests) and [source/compiler/tests/CMakeLists.txt](https://github.com/Southclaws/pawn/blob/master/source/compiler/tests/CMakeLists.txt) for examples.

**Pull request merged**
