### PR TITLE
debug info for tag mismatch warnings

### PR DESCRIPTION
**Pull request by YashasSamaga**
This commit adds useful information to the "tag mismatch" warning.

**Basic tests:**
```
enum PInfo_t {
Money,
Score
}

TAG_H:func1(TAG_G:arg1 = 5, {TAG_I_1, TAG_I_2, TAG_I_3}:arg2 = 5, {TAG_J_1, TAG_J_2, TAG_J_3}:arg3[] = {1, TAG_J_4:2, TAG_J_5:3}) { return 5; }
func2(arg) { }
main() {
	new TAG_A:var1 = 5;
	new TAG_B:arr1[] = {TAG_B_1:5, TAG_B_2:2};
	new TAG_C:str1[] = "abcdefg";
	new TAG_D:str2[2][] = {"abc", "efg"};
	new TAG_E:arr2[2][] = {{1}, {2}};
	const TAG_F:var2 = TAG_F_1:6;

	func1();
	func1(TAG_G_1:66, 6);
	
	new Money = 5;
	func2(Money);
	func1(TAG_G_1:66)
}
```

```
test.pwn(6) : warning 213: tag mismatch: expected tag(s) "TAG_G", but found "_"
test.pwn(6) : warning 213: tag mismatch: expected tag(s) "TAG_I_1", but found "_"
test.pwn(6) : warning 213: tag mismatch: expected tag(s) "TAG_J_1", but found "_"
test.pwn(6) : warning 213: tag mismatch: expected tag(s) "TAG_J_1", but found "TAG_J_4"
test.pwn(6) : warning 213: tag mismatch: expected tag(s) "TAG_J_1", but found "TAG_J_5"
test.pwn(6) : warning 213: tag mismatch: expected tag(s) "TAG_H", but found "_"
test.pwn(9) : warning 213: tag mismatch: expected tag(s) "TAG_A", but found "_"
test.pwn(10) : warning 213: tag mismatch: expected tag(s) "TAG_B", but found "TAG_B_1"
test.pwn(10) : warning 213: tag mismatch: expected tag(s) "TAG_B", but found "TAG_B_2"
test.pwn(11) : warning 213: tag mismatch: expected tag(s) "TAG_C", but found "_"
test.pwn(12) : warning 213: tag mismatch: expected tag(s) "TAG_D", but found "_"
test.pwn(12) : warning 213: tag mismatch: expected tag(s) "TAG_D", but found "_"
test.pwn(13) : warning 213: tag mismatch: expected tag(s) "TAG_E", but found "_"
test.pwn(13) : warning 213: tag mismatch: expected tag(s) "TAG_E", but found "_"
test.pwn(14) : warning 213: tag mismatch: expected tag(s) "TAG_F", but found "TAG_F_1"
test.pwn(17) : warning 213: tag mismatch: expected tag(s) "TAG_G", but found "TAG_G_1"
test.pwn(17) : warning 213: tag mismatch: expected tag(s) "TAG_I_1" or "TAG_I_2" or "TAG_I_3", but found "_"
test.pwn(20) : warning 213: tag mismatch: expected tag(s) "_", but found "PInfo_t"
test.pwn(21) : warning 213: tag mismatch: expected tag(s) "TAG_G", but found "TAG_G_1"
```

**Bugs found using this PR:**
-- 1.

`tag mismatch: expected tag(s) "TAG_I_1", but found "_"`

`tag mismatch: expected tag(s) "TAG_J_1", but found "_"`

the compiler does not check all tags given inside a `{}` for an argument of a function (#145).

### CODE REVIEW

**Comment by Y-Less** [comment]
I'm somewhat confused by your second found bug.  The issue seems to be in the warning you've added, not the original compiler, so how is that a found bug not an introduced bug?

**Comment by YashasSamaga** [comment]
@Y-Less just added a commit to patch that.

**Comment by YashasSamaga** [comment]
Apart from that, there are certain issues:
1. these warnings bloat the warning window with information which are sometimes obvious
2. there is a lot of repetition of code in the commits

**Comment by Zeex** [comment]
Can you put the tag checking stuff in a separate function? There is a lot of duplication there.

**Comment by YashasSamaga** [comment]
I did want to move them to a function but I'm not sure of the following:
- where to put the function
- what to name it
- function signature

Function signature:
- function which accepts two tag identifiers and two string pointers: sets the string pointers to the correct tag name or "-unknown-"
- function which accepts two tag identifiers and triggers the error inside itself: I think this is not a good way because it hids the `error` function
-there could be better signatures than the ones listed above

**Comment by YashasSamaga** [comment]
I deeply regret for using GitHub's default conflict resolution mechanism.  I should've rebased. I will make another PR after moving the repeating code to a function.

**Comment by YashasSamaga** [comment]
How about this `error(213, get_tagname_byval(rtag), get_tagname_byval(ctag));`?

**Comment by Zeex** [comment]
How about `check_tag_mismatch(lval1, lval2)`?

**Comment by YashasSamaga** [comment]
I have created two functions in `sc1.c`:
```
SC_FUNC void check_tagmismatch(int formaltag,int actualtag,int allowcoerce,int errline);
SC_FUNC void check_tagmismatch_multiple(int formaltags[],int numtags,int actualtag,int errline);
```
I don't know where to place them. If I move them out of `sc1.c`, I'll have to move `find_tag_byval` to `sc.h` (currently a static function).

**Pull request closed without merging**
