### PR TITLE
Make warning 247 work for other operators

### PR DESCRIPTION
**Pull request by Daniel-Cortez**
**What this PR does / why we need it**:
This PR does the following:
* Extends warning 247 (`use of operator "%s" on a "bool:" value`) making it work with other arithmetic and comparison operators, not only with `~`.
  Examples:
```Pawn
if (a) {}      // OK
if (!a) {}     // OK
if (a || b) {} // OK
if (a ^ b) {}  // OK
if (a && b) {} // OK
if (a == b) {} // OK
if (a != b) {} // OK
if (a <= b) {} // warning 247: use of operator "<=" on "bool:" values
if (a >= b) {} // warning 247: use of operator ">=" on "bool:" values
if (a < b) {}  // warning 247: use of operator "<" on "bool:" values
if (a > b) {}  // warning 247: use of operator ">" on "bool:" values
if (~a) {}     // warning 247: use of operator "~" on a "bool:" value; did you mean to use operator "!"?
if (-a) {}     // warning 247: use of operator "-" on a "bool:" value; did you mean to use operator "!"?
if (++a) {}    // warning 247: use of operator "++" on a "bool:" value
if (a++) {}    // warning 247: use of operator "++" on a "bool:" value
if (--a) {}    // warning 247: use of operator "--" on a "bool:" value
if (a--) {}    // warning 247: use of operator "--" on a "bool:" value
if (a * b) {}  // warning 247: use of operator "*" on "bool:" values
if (a / b) {}  // warning 247: use of operator "/" on "bool:" values
if (a % b) {}  // warning 247: use of operator "%" on "bool:" values
if (a + b) {}  // warning 247: use of operator "+" on "bool:" values
if (a - b) {}  // warning 247: use of operator "-" on "bool:" values
if (a << b) {} // warning 247: use of operator "<<" on "bool:" values
if (a >> b) {} // warning 247: use of operator ">>" on "bool:" values
if (a >>> b) {}// warning 247: use of operator ">>>" on "bool:" values
```
* Fixes the compiler calling overloaded operator `++` instead of `--` (see #627).

**Which issue(s) this PR fixes**:

Fixes #

**What kind of pull this is**:

* [ ] A Bug Fix
* [x] A New Feature
* [ ] Some repository meta (documentation, etc)
* [ ] Other

**Additional Documentation**:

### CODE REVIEW

**Comment by Y-Less** [comment]
This would be far better just in an include, the same as `%` for `Float:`.  I don't think tag behaviour should really be hard-coded in the compiler too much (I didn't even know there was a warning for `~`).  `bool:` is a weak tag, this makes it some sort of special-case strongish tag.

**Comment by Daniel-Cortez** [comment]
> this makes it some sort of special-case strongish tag

Well, `bool:` is already kind of a special tag, as it's the only built-in tag (defined with built-in constants `true` and `false`) aside from the default one (`_:`), so I figured there would be no harm in adding extra control for operations on `bool:` values. Also, just in case, I made this warning work only if the operator in question is not overloaded, though I'm not sure why anyone would want to overload operators for `bool:` in the first place (and now that I think about it, I should've probably covered this behavior with tests).

**Comment by Y-Less** [comment]
Yes, I'm also not sure, because it is special in some ways (though I don't think having predefined constants is that special really on its own).

**Comment by Daniel-Cortez** [comment]
So, to sum it up, do you want me to remove this diagnostic completely, or just leave it as-is (for operator `~` only), probably?

Also, I wanted to add a similar diagnostic for comlarisons of `Float:` values with `==` and `!=` being unsafe, as they don't take the epsilon value into account (there is a way to check if rational values are fixed-point or floating-point, fixed-point values shouldn't be affected by such diagnostic), but if I understand you correctly, that would be no good either?

**Comment by Y-Less** [comment]
I don't know, but really no to disabling `==` and `!=` for `Float`!  Though, again, those are defined in includes not the compiler.

**Comment by Daniel-Cortez** [comment]
Added a test to make sure overloaded `bool`-tagged operators don't trigger warning 247. This PR should be ready now.

**Comment by Daniel-Cortez** [comment]
Just tried to build the compiler with the changes from this PR manually in `Release` mode, in order to be double sure everything works, and it seems that the test for overloaded operators (`warning_247_ovl`) fails.
```
1>Running warning_247_ovl... FAILED
1>Test warning_247_ovl failed for the following reason: Error output didn't match
1>
1>Expected errors:
1>
1>
1>
1>Actual errors:
1>
1>warning_247_ovl.pwn(37): warning 203: symbol is never used: "operator--(bool:)"
```
Interestingly, it only fails in `Release` and `MinSizeRel` modes; in `RelWithDebInfo` and `Debug` everything works correctly. Might be some undefined behavior or something.

I'll add a "[WIP]" prefix into the PR title for now, until I find the source of this bug and fix it.

**EDIT:** Seems that the default version of the compiler (3.2.3664) is also affected by this problem, which means the changes from this PR most probably have nothing to do with it.

**EDIT (2):** Created a separate issue for this: #627.

**Comment by Daniel-Cortez** [comment]
The problem should be fixed now, but I'm not sure how to really test the fix, as the problem only occurs on `Release` and `MinSizeRel` builds, and CI services build it in `RelWithDebInfo` mode, which isn't affected.

**Pull request merged**
