### PR TITLE
implemented the #pragma once to the compiler

### PR DESCRIPTION
**Pull request by grivetti**
**What this PR does / why we need it**:

-

**Which issue(s) this PR fixes**:

Fixes issue #419 

**What kind of pull this is**:

* [ ] A Bug Fix
* [ ] A New Feature
* [ ] Some repository meta (documentation, etc)
* [ x] Other

**Additional Documentation**:

Changed the compiler to accept the "#pragma once", also changed the include folder as well to the new feature

### CODE REVIEW

**Comment by Y-Less** [comment]
How is this different to #463 ?  Does it address the issues raised there?  And why are there 4000+ lines changed in sc2.c?

**Comment by grivetti** [comment]
In the parte of the 4 thousand lines changed, I really don't know How that happend, I only changed some

**Comment by Y-Less** [comment]
I suspect it was just some auto-formatting from your editor.

**Comment by YashasSamaga** [comment]
"... to merge 1 commit into [pawn-lang:master](https://github.com/pawn-lang/compiler) from"

master or dev?

**Pull request closed without merging**
