### PR TITLE
remove extra new lines from #warning and #pragma deprecated

### PR DESCRIPTION
**Pull request by YashasSamaga**
The `#warning` and `#pragma deprecated` directives print the new line characters which are part of the user entered string. As the message formats for both these already contain a new line character at the end, the aforementioned directives printed two new lines.

This commit adds code to discard the new line characters from user string.

In case of an allocation failure, the compiler falls back to the old code.

Resolves Issue: #187

### CODE REVIEW

**Comment by Y-Less** [comment]
That's only going to work on Windows, you need to check for all trailing new line types.

**Comment by YashasSamaga** [comment]
The code replaces the first occurrence of '\r' or '\n' with null character. For Windows based systems, the '\r' will be replaced by '\0' (we don't care about the '\n' after the null character) and for Linux based systems, the '\n' will be replaced by '\0'. Modern Mac computers use '\n' for terminating lines and older versions of Mac use '\r'.

The code in the PR replaces the first '\r' or '\n' (whichever comes first) with '\0'.

**Comment by Y-Less** [comment]
OK, maybe I should have read its documentation first, instead of assuming it was like `strpos`.  Sorry.  How does this behave:

```pawn
#warning my \
warning \
message
```

?

**Comment by YashasSamaga** [comment]
The `readline` function concatenates the three lines and passes the "my warning message" as a whole line for parsing, i.e: the `lptr` will point to the concatenated line in the memory. It does not matter to any parsing code whether multiple lines were used.

**Pull request merged**
