### PR TITLE
make it compile on OS X

### PR DESCRIPTION
**Pull request by oscar-broman**
I've tried compiling some simple filterscripts and it seems to be working just fine.

I'm sorry if I made a mess in the CMake file, I'm not very familiar with it!

### CODE REVIEW

**Comment by Zeex** [comment]
@oscar-broman Hey, I've made a few additions to this OS X patch, could you please check if [it (mac-rebase)](https://github.com/Zeex/pawn/tree/mac-rebase) actually compiles/works on OS X?

**Comment by oscar-broman** [comment]
Yeah, just one thing on the latest version:
```
In file included from ~/pawn/source/compiler/sc1.c:68:
~/pawn/source/compiler/lstring.h:13:1: error: conflicting types for
      '__builtin___strlcpy_chk'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/secure/_string.h:105:3: note:
      expanded from macro 'strlcpy'
  __builtin___strlcpy_chk (dest, src, len, __darwin_obsz (dest))
```
Related issue: https://github.com/dvarrazzo/py-setproctitle/pull/4

It could be fixed by just adding ` || defined __APPLE__` to `source/compiler/lstring.h:5`.

**Comment by oscar-broman** [comment]
Neat. It works now.

**Comment by Zeex** [comment]
Great, thanks.

**Pull request closed without merging**
