### PR TITLE
allow negative numbers in #emit & changes to public variable behaviour

### PR DESCRIPTION
**Pull request by YashasSamaga**
allows negative numbers in #emit

fix for #125

### CODE REVIEW

**Comment by VVWVV** [comment]
Yes, you are allow to use negative numbers in #emit, but this is only for integer numbers, not floating.
For example, I did this: https://github.com/VVWVV/pawn/commit/880fd101fee5f422e35da3233f5e80f30dc539c2

**Comment by YashasSamaga** [comment]
I don't think someone will ever need to pass a rational value to an assembly instruction.

**Comment by Y-Less** [comment]
I guess they would if they wanted to do:

```pawn
#emit PUSH.C 0.5
#emit PUSH.C 7.7
#emit PUSH.C 8
#emit SYSREQ.C floatmul
```

But that seems more likely to cause confusion and mistakes since there is no tag checking so a stray `.` won't be flagged and will vastly alter the result.

**Comment by Zeex** [comment]
@YashasSamaga Mind fixing Appveyor build and indentation?

**Comment by YashasSamaga** [comment]
1. AppVeyor requires the code to abide by the C89 declaration rules. Moved the s2 declaration to the start of the block.

2. Indentation Fixed. I have a doubt with the indentation for line 755 in sc6 ('else'). I am not sure how you prefer to indent else with single statement. You can edit it.

**Comment by Zeex** [comment]
Great, thanks. 

Yes, Visual Studio doesn't support C99, and in fact the whole codebase is written in C89, so I try to stick to it too (I think it was originally done for maximum portability).

**Pull request merged**
